### ISSUE TITLE
Panel Component examples on fabric site blocked by other elements

### ISSUE THREAD

**Issue by ferrx** [OfficeDev/office-ui-fabric-js#140] opened 2016-10-02 22:28 UTC
Not sure if this is the right repo to post this issue, but I am seeing a problem here http://dev.office.com/fabric#/components/panel

When the panel is displayed, it is partially blocked by the page header's content div and the office-dev-center banner's div. This prevents users from accessing the close commands, etc, forcing a page refresh to get page functionality back. 

I saw that the z-index for the blocking divs was 600, and the panel div's z-index was 300. Changing it (the div with ms-Panel class) from 300 to 700 in F12 fixed the issue.

Tested on Chrome.

**Comment by ericthompson** [comment] 2016-10-04 17:23
Thanks for reporting this, @ferrx. We're investigating now and looking to fix this for the site specifically as the Panel component uses the Layer component and we'd like to fix the source of the problem.

We apologize for the inconvenience!

**Comment by leddie24** [comment] 2016-10-21 22:39
Should be fixed.  If this problem is still occurring can you do a hard refresh on your browser?  Update us if the problem is still there, thanks!

**Closed by leddie24** 2016-10-21 22:39 UTC
Labels: bug, documentation

**Comment by ferrx** [comment] 2016-10-31 12:13
@leddie24 Works great now, thanks!
