### ISSUE TITLE
Version 2.6.1 is no longer on bower

### ISSUE THREAD

**Issue by gabbsmo** [OfficeDev/office-ui-fabric-js#283] opened 2017-02-03 12:08 UTC
Today our CI broke because of an error from bower. It seems that the version the [documentation](https://github.com/OfficeDev/office-ui-fabric-js/blob/master/ghdocs/PACKAGES.md) refers to has been removed.

```
PS C:\foo\bar> bower info office-ui-fabric-js#2.6.1
bower office-ui-fabric-js#2.6.1 cached https://github.com/OfficeDev/office-ui-fabric-js.git#2.6.1
bower office-ui-fabric-js#2.6.1         validate 2.6.1 against https://github.com/OfficeDev/office-ui-fabric-js.git#2.6.1
bower office-ui-fabric-js#2.6.1     ENORESTARGET No tag found that was able to satisfy 2.6.1

Additional error details:
Available versions in https://github.com/OfficeDev/office-ui-fabric-js.git: 1.3.0, 1.2.0, 1.1.0, 1.1.0, 1.0.0
```

**Comment by Jahnp** [comment] 2017-02-03 14:40
Hey @gabbsmo, so sorry for the hassle. This is actually because of the solution to #260. 

The problem is that the Fabric JS repo was copied from [Fabric Core](https://github.com/OfficeDev/office-ui-fabric-core/), known at the time as simply "Office UI Fabric" prior to the restructuring of the projects. *This* repo, Fabric JS, was never intended to include the releases from that repo, since as a new project its versioning was meant to over again at 1.0. 

At the time, we cleaned up the releases in this repo, but due to some unfortunate oversights on our side, those releases kept getting accidentally created with every `git push`--hence #260. To address that issue, we needed to remove the old releases altogether.

Fortunately, all of the "old" releases of Fabric prior to the Core/JS split--including 2.6.2--are still alive and well in the Office UI Fabric Core repo. The solution here is to replace the Bower dependency on Fabric **JS**@2.6.2 with Fabric **Core**@2.6.2: https://github.com/OfficeDev/office-ui-fabric-core/releases/tag/2.6.2. 

Can you give that a shot and let me know if it solves your issue? Unfortunately, we cannot maintain both sets of releases in both repos, since in this case the "old" versioning directly stomps on the "new" versioning, and Bower customers here get broken as a result.

**Comment by gabbsmo** [comment] 2017-02-06 07:12
Hi @Jahnp,,

Thank you for your reply.

Unfortunately this will not work in our case since core 2.6.1 doesn't include the components css files. The latest components css is now js 1.3.0 which is not compatible with our current code base.

We've been using fabric for over a year now, since before it became a proper framework. At one point we wanted to upgrade to the new look and feel in core 5.1.0 but found that our existing code base worked best in combination with js 2.6.1.

I understand that this is a bit unorthodox but we've been using fabric since its early days in a still ongoing project. It was either this or basically rewrite all our css and angular views due to breaking changes in fabric.

**Comment by Jahnp** [comment] 2017-02-06 07:46
Hey @gabbsmo, sorry again for the hassle this has caused you. I understand the frustration, and totally get needing to stick with the older version for the sake of compatibility. Fabric does move pretty quick since it's what we use in our products day in and day out.

In this case, have you taken a look at the 2.6.1 release of Office UI Fabric in the "Core" repo? [Here's the GitHub release](https://github.com/OfficeDev/office-ui-fabric-core/releases/tag/2.6.1), and [here's the commit](https://github.com/OfficeDev/office-ui-fabric-core/commit/33055f2383968f80639a5a0bdca727e1cf68d1d8) so you can browse the built styles. It was the second-to-last release of "Office UI Fabric" prior to the Core and JS projects splitting into two repos, and was the among the last of said releases to include Component styles.

You should be able to install it in your project by running the following command:

`$ bower i https://github.com/OfficeDev/office-ui-fabric-core.git#release/2.6.1 --save`

I just did a fresh install using this command and verified that the component styles are there:

![image](https://cloud.githubusercontent.com/assets/307118/22638465/1eac5aae-ebfd-11e6-8a0b-25755e0a7379.png)

Similarly, you should also be able to update your dependency in `bower.json` to the above URL to solve the issue in your current project. Please give that a shot and let me know if that helps at all! 

While I totally sympathize with the issue you're facing, the releases in the JS repo were actually pushed in error, and should not have been there to begin with since the versioning was to start over from 1.0. I'd really rather not support "duplicate" releases of the same code from separate projects, since they can conflict with other releases (see #260).

**Comment by gabbsmo** [comment] 2017-02-06 11:47
Thank you @Jahnp. I was using the core bower package and did not get the components but with the git url I do. I  can now use the 5.1.0 fabric.css with 2.6.1 components. 

My bower.json in case anyone else have similar problems.
```
"dependencies": {
  "office-ui-fabric-core": "~5.1.0",
  "office-ui-fabric": "https://github.com/OfficeDev/office-ui-fabric-core.git#release/2.6.1"
}
```

**Comment by Jahnp** [comment] 2017-02-17 19:35
Closing for now since this seems to have been resolved on our end. @gabbsmo, please let me know if for some reason this continues to be an issue for you.

**Closed by Jahnp** 2017-02-17 19:35 UTC
