### ISSUE TITLE
misleading document icon type .ms-ListItem-itemIcon--ppt

### ISSUE THREAD

**Issue by gautamsi** [OfficeDev/office-ui-fabric-js#294] opened 2017-02-22 16:13 UTC
commit eda813a039279ee7af4c1a1694054981ba926439 removes the class `ms-ListItem-itemIcon--ppt` long ago but the sample and documentation still usage this.

what is the road map for List Item with document icons? any pointers on how to fix the style?

**Comment by Jahnp** [comment] 2017-02-23 17:13
Hi @gautamsi, thanks for reporting this. It looks like this is a duplicate of #277. @Reezaali can speak to more detail, but in general we'll be looking at making numerous updates to Lists in Fabric JS over the coming months. We will make sure to address this as part of that work. 

I'll go ahead and close this for now, but feel free to comment or re-open if you'd like more help.

**Closed by Jahnp** 2017-02-23 17:13 UTC
